name: validate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate on Node ${{ matrix.node }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    strategy:
      matrix:
        node: ["20.x", "22.x"]
    runs-on: "ubuntu-latest"
    env:
      CI: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@main
        with:
          node-version: ${{ matrix.node }}

      - name: Check formatting and typing
        run: pnpm check

      - name: Run tests
        run: pnpm test:ci

      - name: Run build
        run: pnpm build

  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: labd/gh-actions-typescript/pnpm-install@main

      - name: Run build
        run: pnpm build

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          title: "Release new version"
          commit: "update version"
          publish: pnpm publish:ci
          version: pnpm publish:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
